### ISSUE TITLE
Size option for creating volumes not used.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jorgemoralespou/oc-cluster-wrapper#4]
Code has:

```
  local __size=$2
```

but then doesn't use it in YAML.

```
cat <<-EOF > /tmp/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${__volume}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: ${__path}
EOF
```

So always set to 10Gi.

Only of issue if you wanted to play with what happens when have different sizes. Going to be able to grow beyond that to all available space anyway.
